general:
   collectTelemetryData: false
   jenkinsKubernetes:
    jnlpAgent: 'docker.wdf.sap.corp:50001/sap-production/jnlp-alpine:3.26.1-sap-02'
steps:
  mtaBuild:
    buildTarget: 'NEO'
    dockerImage: 'ppiper/mta-archive-builder:latest'
  neoDeploy:
    dockerImage: 'ppiper/neo-cli:latest'
    account: 'd038702trial'
    host: 'hanatrial.ondemand.com'
    neo: 
      neoCredentialsId: 'NEO_DEPLOY'
